# Bright colors
color8 #6D7070
color9 #FF4352
color10 #B8E466
color11 #FFD750
color12 #1BA6FA
color13 #A578EA
color14 #73FBF1
color15 #FEFEF8

# Normal colors
color0 #0d0d0d
color1 #FF301B
color2 #A0E521
color3 #FFC620
color4 #1BA6FA
color5 #8763B8
color6 #21DEEF
color7 #EBEBEB

# Primary colors (background and foreground)
background #292C3E
foreground #EBEBEB

# Cursor colors
cursor #FF261E

# Font settings
font_family MesloLGS NF
bold_font MesloLGS NF
italic_font MesloLGS NF

font_size 10.0

# Window dimensions
initial_window_width  110c
initial_window_height 30c

# Window opacity (from 0.0 to 1.0, lower values are more transparent)
background_opacity 0.7

