;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │Created By Aditya Shakya @adi1090x                                 │
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[global/wm]
margin-bottom = 0
margin-top = 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

include-file = ~/.config/polybar/cuts/bars.ini
include-file = ~/.config/polybar/cuts/colors.ini
include-file = ~/.config/polybar/cuts/modules.ini
include-file = ~/.config/polybar/cuts/user_modules.ini

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[bar/main]
monitor =

monitor-fallback =

monitor-strict = false

override-redirect = false

bottom = false

fixed-center = true

width = 100%
height = 28

offset-x = 0%
offset-y = 0%

background = ${color.background}

foreground = ${color.foreground}

radius-top = 0.0
radius-bottom = 0.0

line-size = 2
line-color = ${color.primary}

border-size = 0
border-color = ${color.primary}

padding = 0

module-margin-left = 0
module-margin-right = 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

font-0 = Iosevka Nerd Font:style=Medium:size=10;4
font-1 = feather:style=Medium:size=12;3
font-2 = Iosevka Nerd Font:style=Medium:size=19;3
font-3 = Iosevka Nerd Font:style=Medium:size=12;4
font-4 = Iosevka Nerd Font:style=Medium:size=7;4

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[bar/bottom]
inherit = bar/main
monitor = eDP-1
bottom = true
modules-left = spotify decor3 
modules-center = decor2 cpu memory filesystem filesystem_bar temperature battery keyboard decor3
modules-right = decor2 wired-network wireless-network  decor1 decor2 volumess brightness
enable-ipc = true

[bar/tophdmi]
inherit = bar/main
monitor = HDMI-1
modules-left = launcher  decor1 decor2 workspaces decor1 decor2 term files code cursor settings decor1 decor2 color-switch decor1
modules-center = decor4 title decor1
modules-right = decor4 updates decor3  decor4 azan date sysmenu decor3 decor4
enable-ipc = true

[bar/bottomhdmi]
inherit = bar/main
monitor = HDMI-1
bottom = true
modules-left = spotify decor3 
modules-center = decor2 cpu memory filesystem filesystem_bar temperature battery keyboard decor3
modules-right = decor2 wired-network wireless-network decor1 decor2 volumess brightness
enable-ipc = true

[bar/top]
inherit = bar/main
monitor = eDP-1
modules-left = launcher  decor1 decor2 workspaces decor1 decor2 term files code cursor settings decor1 decor2 color-switch decor1
modules-center = decor4 title decor1
modules-right = decor4 updates decor3  decor4 azan date sysmenu decor3 decor4
enable-ipc = true

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

separator =

dim-value = 1.0

wm-name = 

locale = 

tray-position = right

tray-detached = false

tray-maxsize = 16

tray-background = ${color.background-alt}

tray-offset-x = 0
tray-offset-y = 0

tray-padding = 0

tray-scale = 1.0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[settings]
screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
