;; ┌──────────────────────────────────────────────────────────────────────────────-----┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█░█░█▀▀░█▀▀░█▀▄░░░█▄█░█▀█░█▀▄░█░█░█░░░█▀▀░█▀▀ │
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░█░▀▀█░█▀▀░█▀▄░░░█░█░█░█░█░█░█░█░█░░░█▀▀░▀▀█ │
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀░▀░░░▀░▀░▀▀▀░▀▀░░▀▀▀░▀▀▀░▀▀▀░▀▀▀ │
;; │Created By Aditya Shakya @adi1090x                                             │
;; └──────────────────────────────────────────────────────────────────────────────-----┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/updates]
type = custom/script

exec = ~/.config/polybar/cuts/scripts/updates.sh

tail = true

interval = 5

format = <label>
format-prefix = 
format-prefix-foreground = ${color.green}
format-background = ${color.background-alt}
format-padding = 1

label = %output%
label-foreground = ${color.green}

click-left = kitty -e yay -Syyu &
click-right = alacritty -e yay -Syyu &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/launcher]
type = custom/text
content = 

content-background = ${color.background-alt}
content-foreground = ${color.primary}
content-padding = 1

click-left = ~/.config/polybar/cuts/scripts/launcher.sh &
click-right = ~/.config/polybar/cuts/scripts/color-switch.sh &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/sysmenu]
type = custom/text
content = 

content-background = ${color.background-alt}
content-foreground = ${color.primary}
content-padding = 1

click-left = ~/.config/polybar/cuts/scripts/powermenu.sh &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/color-switch]
type = custom/text
content = 

content-background = ${color.background-alt}
content-foreground = ${color.foreground}
content-padding = 1

click-left = ~/.config/polybar/cuts/scripts/style-switch.sh &
click-right = ~/.config/polybar/cuts/scripts/color-switch.sh &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/apps]
type = custom/text
content-background = ${color.background-alt}
content-padding = 1

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/term]
inherit = module/apps
content = 
content-foreground = ${color.yellow}
click-left = kitty &
click-middle = alacritty &
click-right = alacritty &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/files]
inherit = module/apps
content-foreground = ${color.blue}
content = 
click-left = nemo &
click-right = pcmanfm &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/browser]
inherit = module/apps
content-foreground = ${color.orange}
content = 
click-left = brave &
click-right = chromium &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/code]
inherit = module/apps
content-foreground = ${color.purple}
content = 
click-left = code &
click-right = code &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/cursor]
inherit = module/apps
content-foreground = ${color.orange}
content = 
click-left = cursor &
click-right = cursor &


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/settings]
inherit = module/apps
content-foreground = ${color.teal}
content = 
click-left = cinnamon-settings &
click-right = lxappearance &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/powermenu]
type = custom/menu

expand-right = true

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = shutdown
menu-0-1-exec = menu-open-2

menu-1-0 = back
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = systemctl reboot

menu-2-0 = shutdown
menu-2-0-exec = systemctl poweroff
menu-2-1 = back
menu-2-1-exec = menu-open-0

format = <label-toggle> <menu>
format-background = ${color.background-alt}
format-padding = 1

label-open = 
label-close =  

label-separator = " | "

label-open-foreground = ${color.primary}
label-close-foreground = ${color.primary}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/menu]
type = custom/menu

expand-right = true

menu-0-0 = Menu
menu-0-0-exec = ~/.config/polybar/cuts/scripts/launcher.sh &
menu-0-1 = Files
menu-0-1-exec = thunar &
menu-0-2 = Terminal
menu-0-2-exec = termite &
menu-0-3 = Browser
menu-0-3-exec = firefox &

format = <label-toggle> <menu>
format-background = ${color.background-alt}
format-padding = 1

label-open = 
label-close = 

label-separator = " | "

label-open-foreground = ${color.primary}
label-close-foreground = ${color.primary}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/decor-glyph]
type = custom/text
content-background = ${color.background}
content-foreground = ${color.background-alt}

[module/decor1]
inherit = module/decor-glyph
content = "%{T3}%{T-}"

[module/decor2]
inherit = module/decor-glyph
content = "%{T3}%{T-}"

[module/decor3]
inherit = module/decor-glyph
content = "%{T3}%{T-}"

[module/decor4]
inherit = module/decor-glyph
content = "%{T3}%{T-}"

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
